### ISSUE TITLE
Modulo 2.3

### ISSUE THREAD

**Issue by telesfo** [SistemasTecTlaxiaco/noe#10]
![2 3 I](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/acf52928-6bdf-4994-81de-fb44ea7e0793)
![2 3 III](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/91b824fc-bcdd-498b-b2ec-7148aac8b28a)
![2 3 iv](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/9469d297-f55e-465e-a107-7182d7f85e27)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
