### ISSUE TITLE
MODULE 2.4

### ISSUE THREAD

**Issue by telesfo** [SistemasTecTlaxiaco/noe#11]
![2 4 1](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/fa567eb9-4b33-49e3-8249-b0093b7e0966)
![2 4](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/dab7e895-5f23-4cb9-ac26-0ed1379f9b7e)

**Comment by josealfredo79** [comment]
Siga realizando sus actividades...felicidades...
