### ISSUE TITLE
Module 3.1

### ISSUE THREAD

**Issue by telesfo** [SistemasTecTlaxiaco/noe#13]
![3 1](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/4e6340c8-bee8-48b5-8a10-38575bf8344a)
![3 11](https://github.com/SistemasTecTlaxiaco/noe/assets/137822158/34d41056-1a4b-48bd-b4eb-45fe72e2aded)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
